// 存档层：演示数据（订单石位、班组工位容量、裸石、回执、账本）
// 规则、存档与页面分开维护 —— 本文件只提供初始存档

import type { AppState, LedgerEntry } from "../rules/types";

const T = Date.parse("2026-09-28T09:00:00+08:00");

export function buildSeedState(): AppState {
  const orders = [
    { id: "ord_001", orderNo: "DD-2026-001", customer: "「晨曦」高级项链", stonePositions: 4 },
    { id: "ord_002", orderNo: "DD-2026-002", customer: "「星芒」订婚戒指", stonePositions: 3 },
    { id: "ord_003", orderNo: "DD-2026-003", customer: "「繁花」钻石手链", stonePositions: 5 },
  ];

  const teams = [
    { id: "team_a", name: "班组A（镶嵌一组）", workstationCapacity: 3 },
    { id: "team_b", name: "班组B（镶石二组）", workstationCapacity: 2 },
    { id: "team_c", name: "班组C（微镶三组）", workstationCapacity: 2 },
  ];

  const stones = [
    {
      id: "st_2048",
      stoneNo: "ST-2048",
      batchNo: "B2026-0901",
      type: "蓝宝石",
      shape: "椭圆6x4mm",
      carat: 1.2,
      size: "6x4mm",
      clarity: "VS",
      color: "矢车菊蓝",
      cut: "椭圆刻面",
      settingPosition: "主石位",
      defectNote: "无明显缺陷，亭部干净",
      review: "qualified" as const,
      insurance: 50000,
      status: "in_queue" as const,
      orderId: "ord_001",
      teamId: "team_a",
      seq: 1,
      retries: 0,
      operator: "王师傅",
      updatedAt: T,
    },
    {
      id: "st_2061",
      stoneNo: "ST-2061",
      batchNo: "B2026-0901",
      type: "钻石",
      shape: "圆形0.08ct",
      carat: 0.08,
      size: "2.8mm",
      clarity: "SI",
      color: "H",
      cut: "明亮式",
      settingPosition: "围石A组",
      defectNote: "腰棱处小磨损，不影响镶嵌",
      review: "qualified" as const,
      insurance: 8000,
      status: "in_queue" as const,
      orderId: "ord_001",
      teamId: "team_a",
      seq: 2,
      retries: 0,
      operator: "王师傅",
      updatedAt: T,
    },
    {
      id: "st_2077",
      stoneNo: "ST-2077",
      batchNo: "B2026-0902",
      type: "祖母绿",
      shape: "梨形5x3mm",
      carat: 0.6,
      size: "5x3mm",
      clarity: "VS",
      color: "木佐绿",
      cut: "梨形刻面",
      settingPosition: "主石位",
      defectNote: "内部包体，镶口需遮挡",
      review: "qualified" as const,
      insurance: 30000,
      status: "in_queue" as const,
      orderId: "ord_002",
      teamId: "team_a",
      seq: 3,
      retries: 0,
      operator: "李师傅",
      updatedAt: T,
    },
    {
      id: "st_2083",
      stoneNo: "ST-2083",
      batchNo: "B2026-0902",
      type: "红宝石",
      shape: "椭圆4x3mm",
      carat: 0.4,
      size: "4x3mm",
      clarity: "VS",
      color: "鸽血红",
      cut: "椭圆刻面",
      settingPosition: "围石B组",
      defectNote: "无明显缺陷",
      review: "qualified" as const,
      insurance: 12000,
      status: "waitlisted" as const,
      orderId: "ord_002",
      teamId: "team_a",
      seq: 4,
      retries: 0,
      operator: "李师傅",
      updatedAt: T,
    },
    {
      id: "st_2099",
      stoneNo: "ST-2099",
      batchNo: "B2026-0903",
      type: "祖母绿",
      shape: "梨形4x3mm",
      carat: 0.5,
      size: "4x3mm",
      clarity: "内含物明显",
      color: "浅绿",
      cut: "梨形刻面",
      settingPosition: "需客户确认位",
      defectNote: "内含物明显，已备注需客户确认",
      review: "pending" as const,
      insurance: 0,
      status: "pending_confirm" as const,
      orderId: "ord_003",
      teamId: "team_b",
      seq: 5,
      retries: 1,
      operator: "张师傅",
      updatedAt: T,
    },
    {
      id: "st_2105",
      stoneNo: "ST-2105",
      batchNo: "B2026-0903",
      type: "钻石",
      shape: "圆形0.1ct",
      carat: 0.1,
      size: "3mm",
      clarity: "VS",
      color: "G",
      cut: "明亮式",
      settingPosition: "主石位",
      defectNote: "无明显缺陷",
      review: "qualified" as const,
      insurance: 20000,
      status: "in_queue" as const,
      orderId: "ord_003",
      teamId: "team_b",
      seq: 6,
      retries: 0,
      operator: "张师傅",
      updatedAt: T,
    },
    {
      id: "st_2112",
      stoneNo: "ST-2112",
      batchNo: "B2026-0899",
      type: "蓝宝石",
      shape: "椭圆4x3mm",
      carat: 0.45,
      size: "4x3mm",
      clarity: "SI",
      color: "浅蓝",
      cut: "椭圆刻面",
      settingPosition: "围石C组",
      defectNote: "裂纹明显，复核不合格",
      review: "unqualified" as const,
      insurance: 0,
      status: "returned" as const,
      orderId: null,
      teamId: null,
      seq: 0,
      retries: 0,
      operator: "王师傅",
      updatedAt: T,
    },
    {
      id: "st_2118",
      stoneNo: "ST-2118",
      batchNo: "B2026-0904",
      type: "紫水晶",
      shape: "梨形6x4mm",
      carat: 1.5,
      size: "6x4mm",
      clarity: "VS",
      color: "紫罗兰",
      cut: "梨形刻面",
      settingPosition: "主石位",
      defectNote: "待复核，底面有轻微划痕",
      review: "pending" as const,
      insurance: 0,
      status: "in_batch" as const,
      orderId: null,
      teamId: null,
      seq: 0,
      retries: 0,
      operator: "—",
      updatedAt: T,
    },
    {
      id: "st_2120",
      stoneNo: "ST-2120",
      batchNo: "B2026-0904",
      type: "托帕石",
      shape: "祖母绿切5x3mm",
      carat: 0.7,
      size: "5x3mm",
      clarity: "VVS",
      color: "瑞士蓝",
      cut: "祖母绿切",
      settingPosition: "围石D组",
      defectNote: "无明显缺陷",
      review: "qualified" as const,
      insurance: 6000,
      status: "in_batch" as const,
      orderId: null,
      teamId: null,
      seq: 0,
      retries: 0,
      operator: "—",
      updatedAt: T,
    },
  ];

  const receipts = [
    {
      id: "rcp_seed_001",
      stoneId: "st_2099",
      batchNo: "B2026-0903",
      orderId: "ord_003",
      teamId: "team_b",
      retries: 1,
      status: "pending" as const,
      error: "复核结论待确认，禁止写入队列",
      createdAt: T,
      updatedAt: T,
    },
  ];

  const ledger: LedgerEntry[] = [
    {
      id: "led_seed_001",
      seq: 1,
      timestamp: T,
      operator: "系统",
      batchNo: "B2026-0901",
      stoneId: "st_2048",
      orderId: "ord_001",
      teamId: "team_a",
      action: "position_occupied",
      before: null,
      after: { status: "position_held", orderId: "ord_001" },
      retries: 0,
      note: "占用订单 DD-2026-001 石位",
    },
    {
      id: "led_seed_002",
      seq: 2,
      timestamp: T,
      operator: "系统",
      batchNo: "B2026-0901",
      stoneId: "st_2048",
      orderId: "ord_001",
      teamId: "team_a",
      action: "enqueued",
      before: { status: "position_held" },
      after: { status: "in_queue", teamId: "team_a" },
      retries: 0,
      note: "写入班组A当班队列",
    },
    {
      id: "led_seed_003",
      seq: 3,
      timestamp: T,
      operator: "系统",
      batchNo: "B2026-0902",
      stoneId: "st_2083",
      orderId: "ord_002",
      teamId: "team_a",
      action: "waitlisted",
      before: { status: "position_held" },
      after: { status: "waitlisted", teamId: "team_a" },
      retries: 0,
      note: "班组A工位容量不足，按候补顺序排队",
    },
    {
      id: "led_seed_004",
      seq: 4,
      timestamp: T,
      operator: "系统",
      batchNo: "B2026-0903",
      stoneId: "st_2099",
      orderId: "ord_003",
      teamId: "team_b",
      action: "write_failed",
      before: { status: "position_held" },
      after: { status: "pending_confirm", teamId: "team_b" },
      retries: 0,
      note: "复核结论待确认，写入失败，保留待确认回执",
    },
    {
      id: "led_seed_005",
      seq: 5,
      timestamp: T,
      operator: "系统",
      batchNo: "B2026-0903",
      stoneId: "st_2099",
      orderId: "ord_003",
      teamId: "team_b",
      action: "retry_failed",
      before: { status: "pending_confirm" },
      after: { status: "pending_confirm" },
      retries: 1,
      note: "第 1 次重试仍失败（未重复占用石位）",
    },
    {
      id: "led_seed_006",
      seq: 6,
      timestamp: T,
      operator: "王师傅",
      batchNo: "B2026-0899",
      stoneId: "st_2112",
      orderId: "ord_001",
      teamId: "team_a",
      action: "review_changed",
      before: { review: "pending" },
      after: { review: "unqualified" },
      retries: 0,
      note: "复核结论 待复核 → 不合格",
    },
    {
      id: "led_seed_007",
      seq: 7,
      timestamp: T,
      operator: "王师傅",
      batchNo: "B2026-0899",
      stoneId: "st_2112",
      orderId: null,
      teamId: null,
      action: "returned_to_batch",
      before: { status: "in_queue", teamId: "team_a", orderId: "ord_001" },
      after: { status: "returned", teamId: null, orderId: null },
      retries: 0,
      note: "复核不合格，退回原批次 B2026-0899",
    },
  ];

  return {
    stones,
    orders,
    teams,
    receipts,
    ledger,
    seq: 6,
    ledgerSeq: 7,
  };
}
